version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: soccer_ai_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "9000"
    ports:
      - "5173:5173"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=soccer_ai
      - DB_USERNAME=soccer_ai_user
      - DB_PASSWORD=soccer_ai_password

  db:
    image: postgres:15
    container_name: soccer_ai_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: soccer_ai
      POSTGRES_USER: soccer_ai_user
      POSTGRES_PASSWORD: soccer_ai_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webserver:
    image: nginx:alpine
    container_name: soccer_ai_webserver
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  postgres_data: 